CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    employee_code VARCHAR(20) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,

    country VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    job_title VARCHAR(150) NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_employees_employee_code UNIQUE (employee_code),
    CONSTRAINT uk_employees_email UNIQUE (email)
);

CREATE TABLE salary_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    employee_id BIGINT NOT NULL,
    amount NUMERIC(19, 4) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    effective_from DATE NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_salary_history_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(id)
        ON DELETE CASCADE,

    CONSTRAINT uk_salary_history_employee_effective_date
        UNIQUE (employee_id, effective_from),

    CONSTRAINT chk_salary_history_amount_positive
        CHECK (amount > 0),

    CONSTRAINT chk_salary_history_currency_format
        CHECK (currency = UPPER(currency) AND LENGTH(currency) = 3)
);

CREATE INDEX idx_employees_country
    ON employees(country);

CREATE INDEX idx_employees_department
    ON employees(department);

CREATE INDEX idx_salary_history_employee_effective
    ON salary_history(employee_id, effective_from DESC);